function error(){
	try{
		asdasD
	}
	catch(exception){
		console.log(String(exception))
	}
	console.log('Dod not exit abruptly')
}
error()
console.log('Hrllo')

